#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    proprietary/vendor/oneplus/camera-sm8850-common

PRODUCT_COPY_FILES += \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/etc/init/occe_create.rc:$(TARGET_COPY_OUT_ODM)/etc/init/occe_create.rc \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/etc/init/vendor.oplus.hardware.fido.fido2ca@1.0-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.fido.fido2ca@1.0-service.rc \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/etc/init/vendor.oplus.hardware.fido.fidoca@1.0-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.fido.fidoca@1.0-service.rc \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/etc/permissions/vendor-oplus-hardware-cryptoeng.xml:$(TARGET_COPY_OUT_ODM)/etc/permissions/vendor-oplus-hardware-cryptoeng.xml \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/cryptoeng.b00:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b00 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/cryptoeng.b01:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b01 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/cryptoeng.b02:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b02 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/cryptoeng.b03:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b03 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/cryptoeng.b04:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b04 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/cryptoeng.b05:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b05 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/cryptoeng.b06:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b06 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/cryptoeng.b07:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b07 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/cryptoeng.b08:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b08 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/cryptoeng.mdt:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.mdt \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidoctap.b00:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidoctap.b00 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidoctap.b01:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidoctap.b01 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidoctap.b02:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidoctap.b02 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidoctap.b03:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidoctap.b03 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidoctap.b04:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidoctap.b04 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidoctap.b05:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidoctap.b05 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidoctap.b06:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidoctap.b06 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidoctap.b07:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidoctap.b07 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidoctap.b08:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidoctap.b08 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidoctap.mdt:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidoctap.mdt \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidotap.b00:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidotap.b00 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidotap.b01:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidotap.b01 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidotap.b02:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidotap.b02 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidotap.b03:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidotap.b03 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidotap.b04:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidotap.b04 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidotap.b05:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidotap.b05 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidotap.b06:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidotap.b06 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidotap.b07:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidotap.b07 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidotap.b08:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidotap.b08 \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/odm/firmware/secure_ta/fidotap.mdt:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/fidotap.mdt \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AIMemory/lib/arm64/libaiunit_sdk_core.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMemory/lib/arm64/libaiunit_sdk_core.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AIMemory/lib/arm64/libnoise.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMemory/lib/arm64/libnoise.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AIMemory/lib/arm64/libopluslog.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMemory/lib/arm64/libopluslog.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AIMemory/lib/arm64/libscan_engine_decode.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMemory/lib/arm64/libscan_engine_decode.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AIMemory/lib/arm64/libscan_engine_detect.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMemory/lib/arm64/libscan_engine_detect.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AIMemory/lib/arm64/libtensorflowlite.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMemory/lib/arm64/libtensorflowlite.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AIMemory/lib/arm64/libwb_tables_549543368749780587_1.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMemory/lib/arm64/libwb_tables_549543368749780587_1.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AIMemory/lib/arm64/libwbkit-seckit3.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMemory/lib/arm64/libwbkit-seckit3.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AONService/lib/arm64/libNoTopK.so:$(TARGET_COPY_OUT_PRODUCT)/app/AONService/lib/arm64/libNoTopK.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AONService/lib/arm64/libPOSTPROCESS.so:$(TARGET_COPY_OUT_PRODUCT)/app/AONService/lib/arm64/libPOSTPROCESS.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AONService/lib/arm64/libROTATE90PAD.so:$(TARGET_COPY_OUT_PRODUCT)/app/AONService/lib/arm64/libROTATE90PAD.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AONService/lib/arm64/libaiboost_jni.so:$(TARGET_COPY_OUT_PRODUCT)/app/AONService/lib/arm64/libaiboost_jni.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AONService/lib/arm64/libbitmapUtil.so:$(TARGET_COPY_OUT_PRODUCT)/app/AONService/lib/arm64/libbitmapUtil.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AONService/lib/arm64/libfde.so:$(TARGET_COPY_OUT_PRODUCT)/app/AONService/lib/arm64/libfde.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/app/AONService/lib/arm64/libmemoryhelper.so:$(TARGET_COPY_OUT_PRODUCT)/app/AONService/lib/arm64/libmemoryhelper.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/etc/camera/cdr_aging_set.json:$(TARGET_COPY_OUT_PRODUCT)/etc/camera/cdr_aging_set.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/etc/camera/engineer_camera_config.json:$(TARGET_COPY_OUT_PRODUCT)/etc/camera/engineer_camera_config.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/priv-app/AIUnit/lib/arm64/libaiunit_framework.so:$(TARGET_COPY_OUT_PRODUCT)/priv-app/AIUnit/lib/arm64/libaiunit_framework.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/priv-app/AIUnit/lib/arm64/libaiunit_framework_jni.so:$(TARGET_COPY_OUT_PRODUCT)/priv-app/AIUnit/lib/arm64/libaiunit_framework_jni.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/priv-app/AIUnit/lib/arm64/libaiunit_sdk_core.so:$(TARGET_COPY_OUT_PRODUCT)/priv-app/AIUnit/lib/arm64/libaiunit_sdk_core.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/priv-app/AIUnit/lib/arm64/libc++.so:$(TARGET_COPY_OUT_PRODUCT)/priv-app/AIUnit/lib/arm64/libc++.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/priv-app/AIUnit/lib/arm64/libc++_shared.so:$(TARGET_COPY_OUT_PRODUCT)/priv-app/AIUnit/lib/arm64/libc++_shared.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/priv-app/AIUnit/lib/arm64/libcore_tokenizers.so:$(TARGET_COPY_OUT_PRODUCT)/priv-app/AIUnit/lib/arm64/libcore_tokenizers.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/priv-app/AIUnit/lib/arm64/libdatastore_shared_counter.so:$(TARGET_COPY_OUT_PRODUCT)/priv-app/AIUnit/lib/arm64/libdatastore_shared_counter.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/priv-app/AIUnit/lib/arm64/libdmabufheap.so:$(TARGET_COPY_OUT_PRODUCT)/priv-app/AIUnit/lib/arm64/libdmabufheap.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/product/priv-app/AIUnit/lib/arm64/libopencv_java4.so:$(TARGET_COPY_OUT_PRODUCT)/priv-app/AIUnit/lib/arm64/libopencv_java4.so \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/system/etc/permissions/privapp-permissions-oplus.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-oplus.xml \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/system_ext/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/system_ext/etc/permissions/vendor-oplus-hardware-cryptoeng.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vendor-oplus-hardware-cryptoeng.xml \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/chre_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/chre_dynamic_sensors.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_flight_md.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_flight_md.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_offbody_detect_phone.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_offbody_detect_phone.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    proprietary/vendor/oneplus/camera-sm8850-common/proprietary/vendor/etc/sensors/config/sns_transport_ppe.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_transport_ppe.json

PRODUCT_PACKAGES += \
    liboplusmmdebug \
    vendor.oplus.hardware.cameraextension@1.0 \
    libpenguin \
    libAPSClient-alog-jni \
    libAPSClient-cmd-jni-extension.oplus \
    libAPSClient-cmd-jni \
    libAPSClient-jni \
    libAncFilter_jni \
    libAncHumBokeh-jni \
    libAncHumanDoubleExposure-jni \
    libAncHumanRetain-jni_v2 \
    libAncHumanSegFigureFusion-jni \
    libAncHumanVideo-jni \
    libApsFaceBeautyPreviewProductJni \
    libApsSuperEISPreviewJni \
    libAvatarEngineRender \
    libAvatarEngineRenderNative \
    libCombineLut \
    libCombineLutJni \
    libFileExtender-jni \
    libHdrTransform-platform-jni \
    libHeifEncoderWrapper \
    libHeifWinBufExchg-jni \
    libMsEffectSdk \
    libNativeWinBuffExchange \
    libOplusBlurPreviewJNI \
    libOplusStringJNI-extension.oplus \
    libOplusStringJNI \
    libSuperTextWrapper_system_ext \
    libXDocProcessSDK-jni \
    libXDocProcessSDK_system_ext \
    libYTCommon_system_ext \
    libapssuspend-jni.oplus \
    libarcsoft_panorama_burstcapture \
    libarcsoft_wideselfie \
    libatlasservice \
    libbinauralrenderer_wrapper.qti \
    libbsproxy \
    libcsextimpl \
    libextendfile_system_ext \
    libhoaeffects.qti \
    libhoaeffects_csim \
    libhwuiextimpl \
    libiatlasservice \
    libimmlistservice \
    libjni_burstpmk \
    libjni_wideselfie \
    libjnisingleblur_api \
    libjnistblur_api \
    libjpegdecoder_ext \
    libjpegencoder_ext \
    liblivephoto.frc.jni \
    libmmlistparser \
    libmpbase_system_ext \
    libolc \
    liboplus-uah-client_system_ext \
    liboplusHeifDecoderImpl \
    liboplus_10bitHeif \
    liboplus_heifconverter \
    liboplus_imageprocessing \
    liboplus_multimedia_kernel_event \
    liboplusavenhancements \
    libopluscfgpolicy \
    liboplusheifwriter \
    liboplushwui_jni \
    liboplussfplugin_ccodec \
    libortc_so.oplus \
    libsatellite_audio_jni.oplus \
    libsingle_camera_bokeh2_native \
    libsingle_camera_bokeh_native \
    libskjpegencoderextimpl \
    libsoundtouch.oplus \
    libsoundtouch_jni.oplus \
    libst_mobile \
    libst_sticker_jni \
    libsuperNight.oplus \
    libvr_amb_engine \
    vendor.oplus.hardware.cameraMDM@1.0 \
    vendor.oplus.hardware.cryptoeng-V1-ndk \
    vendor.oplus.hardware.cryptoeng@1.0 \
    lib_cryptoeng_api \
    libfido2_factory \
    libfido_factory \
    libqsee_keybox_ca \
    vendor.oplus.hardware.cryptoeng-V1-ndk_odm \
    vendor.oplus.hardware.cryptoeng@1.0_odm \
    vendor.oplus.hardware.fido.fido2ca-V1-ndk \
    vendor.oplus.hardware.fido.fidoca-V1-ndk \
    camera.oemlayer.v2 \
    libAncHumanSegFigureFusion \
    libOplusSecurity \
    liboplus_cfbt \
    ExtensionsService \
    AIMemory \
    AONService \
    RomUpdate \
    AIUnit \
    OplusAppPlatform \
    OplusCamera \
    OppoGallery2 \
    StdID \
    com.oplus.camera.unit.sdk.adapter \
    com.oplus.camera.unit.sdk \
    vendor.oplus.hardware.cryptoeng-V1-java \
    vendor.oplus.hardware.cryptoeng-V1.0-java \
    manifest_oplus_cryptoeng.xml \
    manifest_oplus_fido.xml \
    manifest_oplus_fido2.xml \
    vendor.oplus.hardware.cryptoeng@1.0-service \
    vendor.oplus.hardware.fido.fido2ca@1.0-service \
    vendor.oplus.hardware.fido.fidoca@1.0-service \
    occe_create
